" ----------------------------------------------------------------------------
" Vim/Neovim Config
" ----------------------------------------------------------------------------

" vim specific configs
if !has('nvim')
  execute 'source' fnamemodify(expand('<sfile>'), ':h').'/vim.vim'
endif

" neovim specific configs
if has('nvim')
  execute 'source' fnamemodify(expand('<sfile>'), ':h').'/neovim.vim'
endif

" source plugins
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/plugins.vim'

" ----------------------------------------------------------------------------
" MARK: - Basic
" ----------------------------------------------------------------------------

" enable scrolling
set mouse=a

" enable syntax highlighting
syntax enable

" Make backspace behave the way it should
set backspace=indent,eol,start

" activate line numbers
set number

" show line number on the cursor position
set ruler

" Remap Esc key
inoremap jj <ESC>

" change leader key
let mapleader=' '

" use system's clipboard
set clipboard=unnamed

" ----------------------------------------------------------------------------
" MARK: - Utilities
" ----------------------------------------------------------------------------

" On pressing tab, insert 2 spaces
set expandtab

" show existing tab with 2 spaces width
set tabstop=2
set softtabstop=2

" when indenting with '>', use 2 spaces width
set shiftwidth=2

" ----------------------------------------------------------------------------
" MARK: - Visuals
" ----------------------------------------------------------------------------

" colorschemes and statusline
set background=dark
colorscheme onedark

" remove scrollbars
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" encoding
set encoding=UTF-8

" ----------------------------------------------------------------------------
" MARK: - Search
" ----------------------------------------------------------------------------

" highlight search results
set hlsearch
" incremental search
set incsearch

" ----------------------------------------------------------------------------
" MARK: - Split Management
" ----------------------------------------------------------------------------

set splitbelow
set splitright

nnoremap <Leader>j <C-W><C-J>
nnoremap <Leader>k <C-W><C-K>
nnoremap <Leader>h <C-W><C-H>
nnoremap <Leader>l <C-W><C-L>

" ----------------------------------------------------------------------------
" MARK: - Mappings
" ----------------------------------------------------------------------------

" edit vimrc in a new tab
nnoremap <Leader>ev :tabedit ~/.vim/config/vimrc<cr>
" source vimrc
nnoremap <leader>sv :source $MYVIMRC<cr>

" turn off search highlight
nnoremap <Leader><space> :nohlsearch<cr>

" vertical split
nnoremap <Leader>vsp :vsplit<cr>
" horizontal split
nnoremap <Leader>sp :split<cr>

" ----------------------------------------------------------------------------
" MARK: - Plugin Specifics
" ----------------------------------------------------------------------------

" /
" / NERDTree
" /

" make NERDTreeToggle
nnoremap <Leader>nt :NERDTreeToggle<cr>
" find in NERDTree
nnoremap <Leader>nf :NERDTreeFind<cr>
" disable nerdtree for file browsing
let NERDTreeHijackNetrw = 0

" /
" / fzf
" /

" search git files in project
nnoremap ; :GFiles<CR>
" search files in project
nnoremap <Leader>ff :Files<CR>
" search pattern in project
nnoremap <Leader>ag :Ag<CR>

" /
" / lightline
" /

" lightline config
let g:lightline = {
      \ 'colorscheme': 'onedark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }
" fix lightline not showing in vim
set laststatus=2

" /
" / gitgutter
" /

" remap hunk commands
nnoremap ghp <Plug>GitGutterPreviewHunk
nnoremap ghs <Plug>GitGutterStageHunk
nnoremap ghu <Plug>GitGutterUndoHunk

" ----------------------------------------------------------------------------
" MARK: - Auto-Commands
" ----------------------------------------------------------------------------
